### ISSUE TITLE
no support for ls --color=auto on mac osx bash4

### ISSUE THREAD

**Issue by jaruserickson** [roytenberg/brilliant-bash#14]
throws the following:
ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]

macs BSD version of `ls` lacks `--color` and uses `-G` instead

**Comment by jaruserickson** [comment]
kinda unfortunate linux's ls uses -G for removing the group from ls -l

**Comment by roytenberg** [comment]
Wow, unexpected. Will fix, thanks for bringing it up!

**Comment by roytenberg** [comment]
Hey @jaruserickson, pull the most .bashrc in a few minutes, and give it a go. I'll close it if it works.

**Comment by jaruserickson** [comment]
add fi after the end of the else block

```
else
    ...
fi
```
and i'm getting `Darwin: command not found`

**Comment by jaruserickson** [comment]
it works after the syntax stuff

**Comment by jaruserickson** [comment]
i just submitted a pull request with these fixes.

and mac osx does not suck 😵

**Comment by roytenberg** [comment]
Should be good to go now, right?

**Comment by jaruserickson** [comment]
yep
