### ISSUE TITLE
.bash_aliases

### ISSUE THREAD

**Issue by RayWillett** [roytenberg/brilliant-bash#20]
Should the name of the bash file not be ".bash_aliases" instead of ".bashrc"? It's not a big deal, I'm just curious that there may be something I don't know about going on :)

**Comment by roytenberg** [comment]
Definitely the smarter way to do things. I'll go ahead and just leave the non-interactive check in the .bashrc, and move all of the other aliases into a .bash_aliases file. Thanks, Ray 👍
